---
controller_execution_environments:
  - name: "ee-casc"
    image: lb-hub-pro.lab.example.com/ee-casc:v2.0
    pull: always
    credential: "{{ orgs }} {{ env }} Automation Private Hub Container Registry"
...
