---
controller_execution_environments:
  - name: "ee-casc"
    image: lb-hub-dev-site1.lab.example.com/ee-casc:v2.1
    pull: always
    credential: "{{ orgs }} {{ env }} {{ controller_location }} Automation Private Hub Container Registry"
    controller_location: site1

  - name: "ee-casc"
    image: lb-hub-dev-site2.lab.example.com/ee-ca2.1
    pull: always
    credential: "{{ orgs }} {{ env }} {{ controller_location }} Automation Private Hub Container Registry"
    controller_location: site2
...
