---
controller_execution_environments:
  - name: "ee-casc"
    image: ah22.iam.lab/ee-supported-rhel8:latest
    pull: always
    credential: "{{ orgs }} {{ env }} Automation Private Hub Container Registry"
...
