theme: jekyll-theme-cayman
markdown: kramdown
title: Automation Controller configuration Continuous Deployment with CasC
description: Automation Controller configuration Continuous Deployment with CasC

